"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (password !== confirm) { setError("Passwords do not match."); return; } const token = new URLSearchParams(window.location.search).get("token"); const response = await fetch(`${API}/auth/reset-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, newPassword: password }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(Array.isArray(payload.message) ? payload.message[0] : payload.message ?? "Invalid or expired reset token."); else setMessage(payload.message); }
  return <main className="auth-page"><nav className="nav shell auth-nav"><Link className="brand" href="/"><span className="brand-mark"><span /></span><span>Route<span className="brand-accent">Pilot</span></span></Link><Link className="back-link auth-back" href="/auth/login">← Back to login</Link></nav><section className="auth-shell"><div className="auth-story"><p className="eyebrow"><span className="eyebrow-dot" /> Account security</p><h1>Choose a<br /><em>fresh key.</em></h1><p>Use a strong password that you do not reuse on another service.</p></div><div className="auth-card"><div className="auth-card-head"><span className="auth-kicker">ROUTEPILOT ACCOUNT</span><h2>Choose a new password</h2><p>Your reset link is valid for one hour.</p></div><form onSubmit={submit} className="auth-form"><label>New password<input type="password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm password<input type="password" minLength={8} required value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success">{message}</p>}<button className="button button-full auth-submit">Reset password ↗</button></form><p className="auth-switch"><Link href="/auth/login">Return to login</Link></p></div></section></main>;
}
