"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [developmentToken, setDevelopmentToken] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setMessage(""); setDevelopmentToken(""); try { const response = await fetch(`${API}/auth/forgot-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message ?? "Unable to request a reset."); setMessage(payload.message); if (payload.developmentToken) setDevelopmentToken(payload.developmentToken); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to request a reset."); } finally { setLoading(false); } }
  return <main className="auth-page"><nav className="nav shell auth-nav"><Link className="brand" href="/"><span className="brand-mark"><span /></span><span>Route<span className="brand-accent">Pilot</span></span></Link><Link className="back-link auth-back" href="/auth/login">← Back to login</Link></nav><section className="auth-shell"><div className="auth-story"><p className="eyebrow"><span className="eyebrow-dot" /> Account security</p><h1>Back on the<br /><em>right route.</em></h1><p>Request a secure password reset link and continue preparing when you are ready.</p></div><div className="auth-card"><div className="auth-card-head"><span className="auth-kicker">ROUTEPILOT ACCOUNT</span><h2>Reset your password</h2><p>Enter the email connected to your account.</p></div><form onSubmit={submit} className="auth-form"><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required /></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success">{message}</p>}{developmentToken && <div className="auth-dev-token"><strong>Local development token</strong><code>{developmentToken}</code><Link href={`/auth/reset-password?token=${developmentToken}`}>Continue to reset ↗</Link></div>}<button className="button button-full auth-submit" disabled={loading}>{loading ? "Please wait..." : "Send reset link ↗"}</button></form><p className="auth-switch"><Link href="/auth/login">Return to login</Link></p></div></section></main>;
}
