import type { Locale } from "./i18n";

export type HomeCopy = {
  nav: { howItWorks: string; testCentres: string; pricing: string; faq: string; startPractising: string; myAccount: string; logIn: string };
  hero: { title: string; accent: string; description: string; findCentre: string; seeHow: string; proof: string };
  routeCard: { livePreview: string; centre: string; time: string; preparation: string; keyPoints: string; openRoute: string; attention: string; changeLane: string; saved: string };
  trust: { label: string; practiceRoutes: string; testCentres: string; rated: string; access: string };
  stats: { verifiedRoutes: string; BelgianCentres: string; learnerRating: string; accessToPrepare: string };
  preview: { eyebrow: string; title: string; accent: string; description: string; list: string[]; explore: string; examCentre: string; points: string; pointTitles: string[]; pointDetails: string[] };
  testimonials: { eyebrow: string; title: string; accent: string; sideCopy: string; quotes: string[]; passed: string[] };
  faq: { eyebrow: string; title: string; accent: string; intro: string; contact: string; questions: { question: string; answer: string }[] };
  cta: { eyebrow: string; title: string; accent: string; button: string };
  footer: { howItWorks: string; testCentres: string; pricing: string; faq: string; language: string; copyright: string; note: string };
};

export const homeCopy: Record<Locale, HomeCopy> = {
  en: {
    nav: { howItWorks: "How it works", testCentres: "Test centres", pricing: "Pricing", faq: "FAQ", startPractising: "Start practising", myAccount: "My account", logIn: "Log in" },
    hero: { title: "Know the road.", accent: "Drive with confidence.", description: "Explore real practice routes, spot the tricky moments and prepare for your driving test before test day arrives.", findCentre: "Find my test centre", seeHow: "See how it works", proof: "Loved by learner drivers" },
    routeCard: { livePreview: "Live route preview", centre: "BRUSSELS SOUTH", time: "24 min", preparation: "PREPARATION", keyPoints: "7 key points", openRoute: "Open route", attention: "Attention point", changeLane: "Change lane early", saved: "Route saved" },
    trust: { label: "TRUSTED BY LEARNER DRIVERS", practiceRoutes: "practice routes", testCentres: "test centres", rated: "rated by learners", access: "access" },
    stats: { verifiedRoutes: "verified practice routes", BelgianCentres: "Belgian test centres", learnerRating: "learner rating", accessToPrepare: "access to prepare" },
    preview: { eyebrow: "See the details that matter", title: "Your route,", accent: "made clearer.", description: "Every route brings the important moments together in one calm, visual overview. No clutter. No second guessing.", list: ["Ordered route points and start/finish markers", "Warnings for lanes, signs and complex junctions", "Photos, videos and practical driving tips"], explore: "Explore a sample route", examCentre: "EXAM CENTRE · BRUSSELS SOUTH", points: "7 points", pointTitles: ["Start at test centre", "Lane change", "Roundabout"], pointDetails: ["Check mirrors before leaving", "Move over before the junction", "Watch the second exit"] },
    testimonials: { eyebrow: "Learners feel ready sooner", title: "Less stress.", accent: "More confidence.", sideCopy: "Real preparation is knowing what is coming before the first turn.", quotes: ["I knew the difficult junctions before my first practice drive. That changed everything.", "The route points made it easy to focus on the moments that actually matter.", "It gave me a calm plan instead of another list of streets to memorise."], passed: ["Passed first time · Brussels", "Passed first time · Antwerp", "Passed first time · Ghent"] },
    faq: { eyebrow: "Questions, answered", title: "Ready when", accent: "you are.", intro: "Everything you need to know before choosing your first route.", contact: "Still have a question", questions: [{ question: "Are the routes free to discover?", answer: "Yes. You can browse centres and preview routes publicly. A time-based access plan unlocks the complete preparation experience, including every point, warning and media item." }, { question: "Which access periods are available?", answer: "RoutePilot is designed around focused preparation: 1 day, 1 week, 1 month and 3 months. Choose the period that matches your exam date." }, { question: "Can I practise more than one test centre?", answer: "Your access plan will show exactly what is included. The product is built so plans can cover one centre or multiple centres as the business model grows." }, { question: "Are the routes official examiner routes?", answer: "Routes are preparation guides and can change because of roadworks, traffic and local conditions. Always follow current signs, road rules and examiner instructions." }] },
    cta: { eyebrow: "Your next drive can feel different", title: "Turn unfamiliar roads", accent: "into familiar ground.", button: "Find my test centre" },
    footer: { howItWorks: "How it works", testCentres: "Test centres", pricing: "Pricing", faq: "FAQ", language: "EN", copyright: "© 2026 RoutePilot. Prepare well. Drive calmly.", note: "Built for safer, more confident test preparation." },
  },
  nl: {
    nav: { howItWorks: "Hoe het werkt", testCentres: "Examencentra", pricing: "Prijzen", faq: "FAQ", startPractising: "Start met oefenen", myAccount: "Mijn account", logIn: "Inloggen" },
    hero: { title: "Ken de weg.", accent: "Rijd met vertrouwen.", description: "Ontdek echte oefenroutes, herken moeilijke momenten en bereid je voor op je rijexamen.", findCentre: "Vind mijn examencentrum", seeHow: "Bekijk hoe het werkt", proof: "Geliefd bij leerling-bestuurders" },
    routeCard: { livePreview: "Live routevoorbeeld", centre: "BRUSSEL ZUID", time: "24 min", preparation: "VOORBEREIDING", keyPoints: "7 belangrijke punten", openRoute: "Open route", attention: "Aandachtspunt", changeLane: "Wissel tijdig van rijstrook", saved: "Route opgeslagen" },
    trust: { label: "VERTROUWD DOOR LEERLING-BESTUURDERS", practiceRoutes: "oefenroutes", testCentres: "examencentra", rated: "beoordeeld door leerlingen", access: "toegang" },
    stats: { verifiedRoutes: "geverifieerde oefenroutes", BelgianCentres: "Belgische examencentra", learnerRating: "beoordeling door leerlingen", accessToPrepare: "toegang tot je voorbereiding" },
    preview: { eyebrow: "Zie de details die ertoe doen", title: "Jouw route,", accent: "duidelijker gemaakt.", description: "Elke route brengt de belangrijke momenten samen in één rustig, visueel overzicht. Geen ruis. Geen twijfel.", list: ["Geordende routepunten en start-/finishmarkeringen", "Waarschuwingen voor rijstroken, borden en complexe kruispunten", "Foto's, video's en praktische rijtips"], explore: "Bekijk een voorbeeldroute", examCentre: "EXAMENCENTRUM · BRUSSEL ZUID", points: "7 punten", pointTitles: ["Start bij examencentrum", "Rijstrook wisselen", "Rotonde"], pointDetails: ["Controleer je spiegels voordat je vertrekt", "Ga vóór het kruispunt naar de juiste rijstrook", "Let op de tweede afslag"] },
    testimonials: { eyebrow: "Leerlingen voelen zich sneller klaar", title: "Minder stress.", accent: "Meer vertrouwen.", sideCopy: "Een goede voorbereiding betekent weten wat eraan komt vóór de eerste afslag.", quotes: ["Ik kende de moeilijke kruispunten al vóór mijn eerste oefenrit. Dat veranderde alles.", "Dankzij de routepunten kon ik me richten op de momenten die er echt toe doen.", "Ik kreeg een rustig plan in plaats van nog een lijst straten om uit het hoofd te leren."], passed: ["De eerste keer geslaagd · Brussel", "De eerste keer geslaagd · Antwerpen", "De eerste keer geslaagd · Gent"] },
    faq: { eyebrow: "Veelgestelde vragen", title: "Klaar wanneer", accent: "jij dat bent.", intro: "Alles wat je moet weten voordat je je eerste route kiest.", contact: "Heb je nog een vraag?", questions: [{ question: "Kan ik de routes gratis bekijken?", answer: "Ja. Je kunt examencentra bekijken en routes publiek voorvertonen. Met een tijdsgebonden abonnement krijg je toegang tot de volledige voorbereiding, inclusief alle punten, waarschuwingen en media." }, { question: "Welke toegangsperiodes zijn beschikbaar?", answer: "RoutePilot is gemaakt voor gerichte voorbereiding: 1 dag, 1 week, 1 maand en 3 maanden. Kies de periode die bij jouw examendatum past." }, { question: "Kan ik bij meerdere examencentra oefenen?", answer: "Je abonnement toont precies wat inbegrepen is. De dienst is zo opgebouwd dat pakketten één of meerdere examencentra kunnen bevatten." }, { question: "Zijn dit officiële examenroutes?", answer: "Routes zijn voorbereidingsgidsen en kunnen veranderen door wegenwerken, verkeer en lokale omstandigheden. Volg altijd de actuele borden, verkeersregels en instructies van de examinator." }] },
    cta: { eyebrow: "Je volgende rit kan anders voelen", title: "Maak onbekende wegen", accent: "vertrouwd terrein.", button: "Vind mijn examencentrum" },
    footer: { howItWorks: "Hoe het werkt", testCentres: "Examencentra", pricing: "Prijzen", faq: "FAQ", language: "NL", copyright: "© 2026 RoutePilot. Bereid je goed voor. Rijd rustig.", note: "Ontworpen voor een veiligere en zelfverzekerdere examenvoorbereiding." },
  },
};
