import type { Locale } from "./i18n";

type LegalSection = { number: string; title: string; paragraphs?: string[]; bullets?: string[] };
type LegalPageCopy = {
  eyebrow: string;
  title: string;
  accent: string;
  intro: string;
  updated: string;
  scope: string;
  introLabel: string;
  introText: string;
  sections: LegalSection[];
  contactLabel: string;
  contactTitle: string;
  contactText: string;
  contactButton: string;
  disclaimer?: string;
};

export const legalCopy: Record<Locale, { privacy: LegalPageCopy; terms: LegalPageCopy }> = {
  en: {
    privacy: {
      eyebrow: "Privacy at Drive Coach", title: "Your data.", accent: "Your control.", intro: "We collect only what helps you create an account, prepare on real-world routes and understand your own practice. This page explains what happens to that information.", updated: "Last updated: 5 October 2026", scope: "Applies to drive-coach-production.up.railway.app", introLabel: "In short", introText: "Your account and practice information is used to run Drive Coach and personalise your preparation. Optional GPS tracking is used only when you enable it. We do not sell personal data.",
      sections: [
        { number: "01", title: "Information we collect", paragraphs: ["Account details. When you register, we process your name if provided, email address, password credentials and account verification records. Passwords are stored as protected hashes, not as readable passwords.", "Practice information. We store saved routes, practice sessions, completion progress, self-reflection answers, selected difficulty categories and optional instructor notes so your dashboard and Drive Coach recommendations can work.", "Optional location data. If you choose Enable GPS tracking during a practice session, we receive location, accuracy and speed readings to draw your private practice track. GPS is optional and can be stopped at any time.", "Payments and technical events. We store plan, subscription and payment status. Payment providers process card or bank details; Drive Coach does not need to store your full payment-card number. We may record basic page, centre and route events to understand which parts of the service are useful."] },
        { number: "02", title: "How we use information", bullets: ["to create, secure and support your account;", "to show routes, saved centres, practice history and access rights;", "to turn your reflection into personal preparation suggestions;", "to process subscriptions and respond to support requests;", "to detect misuse, protect the platform and improve reliability."], paragraphs: ["Practice reflections are coaching inputs, not an official assessment of your driving ability and not a decision made by an examiner."] },
        { number: "03", title: "Storage, providers and sharing", paragraphs: ["Drive Coach may use hosting, database, map, payment and email providers to operate the service. They receive only the information needed for their role and must protect it under their own terms. We do not sell your information or use practice reflections for advertising.", "Map tiles and map services can receive the requests needed to display a map. Payment information is handled by the payment provider shown at checkout. If an email provider is enabled, it may process messages needed for verification or account recovery."] },
        { number: "04", title: "Cookies and browser storage", paragraphs: ["Drive Coach uses essential browser storage for a signed-in session and language preference. The current app stores access tokens in session storage and the selected language in local storage and a small preference cookie. We do not currently use advertising cookies.", "You can clear browser storage through your browser settings. Clearing session storage signs you out; clearing the language preference resets the site language."] },
        { number: "05", title: "How long we keep information", paragraphs: ["We keep information while it is needed to provide your account, practice history, access and support. We remove or anonymise information when it is no longer needed, unless a longer period is required for security, accounting or legal obligations.", "You can ask us to close your account and delete associated personal information. Some records may need to be retained where the law requires it."] },
        { number: "06", title: "Your privacy rights", paragraphs: ["Depending on your location and applicable law, you may request access, correction, deletion, restriction, portability or objection to certain processing. You may also withdraw consent where processing relies on consent. We may need to verify your identity before completing a request.", "To make a request, contact hello@drivecoach.local. You may also contact your local data-protection authority if you believe your rights have not been respected."] },
      ],
      contactLabel: "PRIVACY QUESTIONS", contactTitle: "Need a clear answer?", contactText: "Tell us which account, route or practice record your question concerns.", contactButton: "Contact Drive Coach", disclaimer: "This policy describes the current Drive Coach product. The operator should keep the business identity, contact details, processors and retention settings updated as the service grows and have the final policy reviewed for the countries where it operates.",
    },
    terms: {
      eyebrow: "Using Drive Coach", title: "Simple rules.", accent: "Safer practice.", intro: "These terms explain how to use Drive Coach routes, coaching tools and paid access responsibly.", updated: "Last updated: 5 October 2026", scope: "Drive Coach platform terms", introLabel: "Before you start", introText: "Drive Coach is a preparation tool. Always follow current traffic signs, road rules and instructions from your official examiner or instructor.",
      sections: [
        { number: "01", title: "Using route content", paragraphs: ["Routes, points, warnings, maps and coaching tips are preparation guidance. They may change because of roadworks, traffic, signs or local conditions. Route information is not a guarantee of the route used in your official test."] },
        { number: "02", title: "Accounts and access", paragraphs: ["Keep your account information accurate and your password private. You are responsible for activity under your account. Paid access lasts for the period shown when you choose a plan; the plan, price, currency and expiry displayed at checkout apply to that purchase."] },
        { number: "03", title: "Safe use while driving", paragraphs: ["Do not interact with the website, map, GPS controls or coaching interface while moving. Stop safely before using the service. GPS tracking is optional and should only be used with appropriate permission and attention to the road."] },
        { number: "04", title: "Payments and digital access", paragraphs: ["Payments are handled through the provider presented at checkout. Digital access may begin after successful payment. Refunds, cancellations or statutory consumer rights are governed by the terms shown at checkout and applicable law."] },
        { number: "05", title: "Responsibility and limitations", paragraphs: ["You remain responsible for safe driving and compliance with current road rules. Drive Coach does not replace an instructor, official examiner or live navigation service, and cannot guarantee that route content is complete, current or error-free."] },
      ],
      contactLabel: "QUESTIONS ABOUT THE TERMS", contactTitle: "Talk to our team.", contactText: "We can clarify access, accounts or route content.", contactButton: "Contact Drive Coach",
    },
  },
  nl: {
    privacy: {
      eyebrow: "Privacy bij Drive Coach", title: "Jouw gegevens.", accent: "Jouw controle.", intro: "We verzamelen alleen wat nodig is om je account te maken, je voor te bereiden op echte routes en inzicht te geven in je eigen oefenritten. Op deze pagina lees je wat er met die informatie gebeurt.", updated: "Laatst bijgewerkt: 5 oktober 2026", scope: "Van toepassing op drive-coach-production.up.railway.app", introLabel: "Kort samengevat", introText: "Je account- en oefengegevens worden gebruikt om Drive Coach te laten werken en je voorbereiding persoonlijker te maken. Optionele GPS-tracking wordt alleen gebruikt wanneer je die inschakelt. We verkopen geen persoonsgegevens.",
      sections: [
        { number: "01", title: "Welke informatie verzamelen we?", paragraphs: ["Accountgegevens. Bij registratie verwerken we je naam als je die invult, e-mailadres, beveiligde wachtwoordgegevens en verificatiegegevens. Wachtwoorden worden als beschermde hashes opgeslagen, nooit als leesbare wachtwoorden.", "Oefengegevens. We bewaren opgeslagen routes, oefensessies, voortgang, antwoorden op zelfreflectie, gekozen aandachtspunten en optionele notities van je instructeur zodat je dashboard en aanbevelingen kunnen werken.", "Optionele locatiegegevens. Als je GPS-tracking tijdens een oefensessie inschakelt, ontvangen we locatie, nauwkeurigheid en snelheid om je persoonlijke oefenspoor te tonen. GPS is optioneel en kan altijd worden gestopt.", "Betalingen en technische gebeurtenissen. We bewaren plan-, abonnement- en betaalstatus. Betaalproviders verwerken kaart- of bankgegevens; Drive Coach hoeft je volledige kaartnummer niet op te slaan. We kunnen basisgebeurtenissen rond pagina's, centra en routes registreren om de dienst te verbeteren."] },
        { number: "02", title: "Hoe gebruiken we informatie?", bullets: ["om je account te maken, beveiligen en ondersteunen;", "om routes, opgeslagen centra, oefengeschiedenis en toegangsrechten te tonen;", "om je reflectie om te zetten in persoonlijke voorbereidingstips;", "om abonnementen te verwerken en supportvragen te beantwoorden;", "om misbruik te detecteren, het platform te beschermen en de betrouwbaarheid te verbeteren."], paragraphs: ["Zelfreflecties zijn input voor coaching. Ze zijn geen officiële beoordeling van je rijvaardigheid en vormen geen beslissing van een examinator."] },
        { number: "03", title: "Opslag, providers en delen", paragraphs: ["Drive Coach kan hosting-, database-, kaart-, betaal- en e-mailproviders gebruiken om de dienst te laten werken. Zij ontvangen alleen de informatie die nodig is voor hun rol en moeten die volgens hun eigen voorwaarden beschermen. We verkopen je informatie niet en gebruiken oefenreflecties niet voor reclame.", "Kaarttegels en kaartdiensten kunnen de verzoeken ontvangen die nodig zijn om een kaart te tonen. Betaalinformatie wordt verwerkt door de betaalprovider die bij het afrekenen wordt getoond. Als een e-mailprovider actief is, kan die berichten voor verificatie of accountherstel verwerken."] },
        { number: "04", title: "Cookies en browseropslag", paragraphs: ["Drive Coach gebruikt noodzakelijke browseropslag voor een ingelogde sessie en je taalvoorkeur. De app bewaart toegangstokens in session storage en de gekozen taal in local storage en een kleine voorkeurcookie. We gebruiken momenteel geen advertentiecookies.", "Je kunt browseropslag wissen via je browserinstellingen. Als je session storage wist, word je uitgelogd; als je de taalvoorkeur wist, wordt de standaardtaal hersteld."] },
        { number: "05", title: "Hoe lang bewaren we informatie?", paragraphs: ["We bewaren informatie zolang die nodig is voor je account, oefengeschiedenis, toegang en ondersteuning. Daarna verwijderen of anonimiseren we informatie, behalve wanneer een langere periode nodig is voor veiligheid, administratie of wettelijke verplichtingen.", "Je kunt vragen om je account te sluiten en de bijbehorende persoonsgegevens te verwijderen. Sommige gegevens moeten mogelijk bewaard blijven wanneer de wet dat voorschrijft."] },
        { number: "06", title: "Je privacyrechten", paragraphs: ["Afhankelijk van je locatie en de toepasselijke wetgeving kun je inzage, correctie, verwijdering, beperking, overdraagbaarheid of bezwaar tegen bepaalde verwerking vragen. Je kunt ook toestemming intrekken wanneer verwerking daarop is gebaseerd. We kunnen je identiteit moeten controleren voordat we een verzoek uitvoeren.", "Neem voor een verzoek contact op via hello@drivecoach.local. Je kunt ook contact opnemen met je lokale privacytoezichthouder als je vindt dat je rechten niet zijn gerespecteerd."] },
      ],
      contactLabel: "PRIVACYVRAGEN", contactTitle: "Wil je een duidelijk antwoord?", contactText: "Vertel ons over welk account, welke route of welke oefensessie je vraag gaat.", contactButton: "Neem contact op", disclaimer: "Dit beleid beschrijft de huidige Drive Coach-productversie. De beheerder moet bedrijfsgegevens, contactgegevens, verwerkers en bewaartermijnen bijwerken naarmate de dienst groeit en het definitieve beleid laten beoordelen voor de landen waarin de dienst actief is.",
    },
    terms: {
      eyebrow: "Drive Coach gebruiken", title: "Duidelijke regels.", accent: "Veiliger oefenen.", intro: "Deze voorwaarden leggen uit hoe je Drive Coach-routes, coachingtools en betaalde toegang verantwoord gebruikt.", updated: "Laatst bijgewerkt: 5 oktober 2026", scope: "Voorwaarden van het Drive Coach-platform", introLabel: "Voordat je begint", introText: "Drive Coach is een voorbereidingstool. Volg altijd de actuele verkeersborden, verkeersregels en instructies van je officiële examinator of instructeur.",
      sections: [
        { number: "01", title: "Route-inhoud gebruiken", paragraphs: ["Routes, punten, waarschuwingen, kaarten en coachingtips zijn bedoeld als voorbereiding. Ze kunnen veranderen door wegwerkzaamheden, verkeer, borden of lokale omstandigheden. Route-informatie garandeert niet welke route je tijdens het officiële examen krijgt."] },
        { number: "02", title: "Accounts en toegang", paragraphs: ["Houd je accountgegevens juist en je wachtwoord privé. Je bent verantwoordelijk voor activiteit onder je account. Betaalde toegang duurt zolang als bij het kiezen van een plan wordt getoond; plan, prijs, valuta en vervaldatum bij het afrekenen gelden voor die aankoop."] },
        { number: "03", title: "Veilig gebruik tijdens het rijden", paragraphs: ["Gebruik de website, kaart, GPS-bediening of coachinginterface niet terwijl je rijdt. Stop op een veilige plaats voordat je de dienst gebruikt. GPS-tracking is optioneel en mag alleen worden gebruikt met de juiste toestemming en aandacht voor de weg."] },
        { number: "04", title: "Betalingen en digitale toegang", paragraphs: ["Betalingen worden verwerkt via de provider die bij het afrekenen wordt getoond. Digitale toegang kan starten na een geslaagde betaling. Terugbetalingen, annuleringen en wettelijke consumentenrechten vallen onder de voorwaarden bij het afrekenen en de toepasselijke wetgeving."] },
        { number: "05", title: "Verantwoordelijkheid en beperkingen", paragraphs: ["Je blijft verantwoordelijk voor veilig rijden en het volgen van de actuele verkeersregels. Drive Coach vervangt geen instructeur, officiële examinator of live navigatiedienst en kan niet garanderen dat route-inhoud volledig, actueel of foutloos is."] },
      ],
      contactLabel: "VRAGEN OVER DE VOORWAARDEN", contactTitle: "Praat met ons team.", contactText: "We leggen toegang, accounts of route-inhoud graag uit.", contactButton: "Neem contact op",
    },
  },
};
