import type { Locale } from "./i18n";

export type SiteCopy = {
  footer: {
    description: string;
    testCentres: string;
    guides: string;
    contact: string;
    privacy: string;
    terms: string;
    copyright: string;
    tagline: string;
  };
  chatbot: {
    welcome: string;
    quickLabel: string;
    quickPrompts: string[];
    routeAware: string;
    close: string;
    open: string;
    placeholder: string;
    messageLabel: string;
    disclaimer: string;
    temporaryUnavailable: string;
    emptyAnswer: string;
  };
  auth: {
    backHome: string;
    prepareClarity: string;
    storyTitle: string;
    storyAccent: string;
    storyDescription: string;
    routeCount: string;
    accountKicker: string;
    createTitle: string;
    welcomeTitle: string;
    createDescription: string;
    loginDescription: string;
    fullName: string;
    yourName: string;
    email: string;
    emailPlaceholder: string;
    password: string;
    passwordPlaceholder: string;
    remember: string;
    forgot: string;
    wait: string;
    createAccount: string;
    login: string;
    alreadyAccount: string;
    newToDriveCoach: string;
    termsNote: string;
    accountCreated: string;
    genericError: string;
    apiError: string;
    accountSecurity: string;
    securityTitle: string;
    securityAccent: string;
    resetDescription: string;
    resetTitle: string;
    resetSubtitle: string;
    sendReset: string;
    returnLogin: string;
    localToken: string;
    continueReset: string;
    newPassword: string;
    confirmPassword: string;
    resetPassword: string;
    passwordMismatch: string;
    invalidReset: string;
    verificationTitle: string;
    verificationAccent: string;
    verificationDescription: string;
    verificationContinue: string;
    verifying: string;
    noVerificationToken: string;
    invalidVerification: string;
    unableConnect: string;
  };
  about: { eyebrow: string; title: string; accent: string; intro: string; approach: string; approachTitle: string; bodyOne: string; bodyTwo: string };
  blog: { eyebrow: string; title: string; accent: string; intro: string; explore: string; guides: Array<{ tag: string; title: string; text: string }> };
  contact: { eyebrow: string; title: string; accent: string; intro: string; support: string; supportTitle: string; supportText: string; email: string; quickLinks: string; quickTitle: string; quickText: string; faq: string; centres: string };
  account: { eyebrow: string; title: string; description: string; active: string; verified: string; created: string; free: string; premium: string; premiumActive: string; freeDescription: string; premiumDescription: string; validUntil: string; actions: string; billing: string; billingTitle: string; secureCheckout: string; billingIntro: string; choosePlan: string; opening: string; noPlans: string; paymentHistory: string; invoices: string };
  dashboard: { eyebrow: string; title: string; accent: string; description: string; explore: string; smallHabits: string; access: string; premiumActive: string; freeActive: string; viewPlans: string; manageAccount: string; attentionPoints: string; noSaved: string; findCentre: string; reflect: string; complete: string; inProgress: string; inbox: string; markRead: string };
  route: { allCentres: string; routeExperience: string; updated: string; preview: string; sequence: string; mappedPreview: string; openGoogle: string; selectedPoint: string; whatWatch: string; shown: string; fullRoute: string; previewPoints: string; unlockTitle: string; unlockText: string; chooseAccess: string; unlocked: string; unlockedText: string; practiceRoutes: string; keyPoints: string; chooseRun: string; around: string; freeRoute: string; premiumRoutes: string; routePreparing: string; viewRoute: string; unlockRoute: string; disclaimer: string; previewNotConnected: string; save: string; saved: string; completePractice: string; startPractice: string; enableGps: string; stopGps: string; savedRoute: string; removedRoute: string; updateSavedError: string; sessionStarted: string; startError: string; sessionCompleted: string; finishError: string; reflectionPrompt: string; locationUnsupported: string; permissionDenied: string; gpsEnabled: string; savedProgress: string; previewRoute: string; selectedPointFallback: string; practiceRouteLegend: string; attentionPoints: string };
};

export const siteCopy: Record<Locale, SiteCopy> = {
  en: {
    footer: { description: "Clear route preparation for calmer, more confident test days.", testCentres: "Test centres", guides: "Guides", contact: "Contact", privacy: "Privacy", terms: "Terms", copyright: "© 2026 Drive Coach", tagline: "Practise with attention. Follow the road in front of you." },
    chatbot: { welcome: "Hi, I’m Drive Coach AI. Ask me about your route, roundabouts, observation, speed or how to prepare for test day.", quickLabel: "Try asking", quickPrompts: ["How should I prepare for my test?", "What should I watch for at roundabouts?", "How can I improve my observation?"], routeAware: "Route-aware practice coach", close: "Close AI chat", open: "Open Drive Coach AI", placeholder: "Ask about your driving practice…", messageLabel: "Message Drive Coach AI", disclaimer: "AI guidance is for practice preparation. Always follow your instructor and local road rules.", temporaryUnavailable: "The AI coach is temporarily unavailable.", emptyAnswer: "I’m sorry, I could not answer that just now." },
    auth: { backHome: "Back to home", prepareClarity: "Prepare with clarity", storyTitle: "Feel ready", storyAccent: "before you start.", storyDescription: "Save your centres, keep your routes close and build confidence one practice drive at a time.", routeCount: "practice routes to explore", accountKicker: "DRIVE COACH ACCOUNT", createTitle: "Create your account", welcomeTitle: "Welcome back", createDescription: "Start preparing for your test with a free account.", loginDescription: "Log in to continue your preparation.", fullName: "Full name", yourName: "Your name", email: "Email address", emailPlaceholder: "you@example.com", password: "Password", passwordPlaceholder: "At least 8 characters", remember: "Remember me", forgot: "Forgot password?", wait: "Please wait…", createAccount: "Create account", login: "Log in", alreadyAccount: "Already have an account?", newToDriveCoach: "New to Drive Coach?", termsNote: "By continuing, you agree to our terms and privacy policy.", accountCreated: "Account created. You can now log in.", genericError: "Something went wrong. Please try again.", apiError: "Unable to connect to the API.", accountSecurity: "Account security", securityTitle: "Back on the", securityAccent: "right route.", resetDescription: "Request a secure password reset link and continue preparing when you are ready.", resetTitle: "Reset your password", resetSubtitle: "Enter the email connected to your account.", sendReset: "Send reset link", returnLogin: "Return to login", localToken: "Local development token", continueReset: "Continue to reset", newPassword: "New password", confirmPassword: "Confirm password", resetPassword: "Reset password", passwordMismatch: "Passwords do not match.", invalidReset: "Invalid or expired reset token.", verificationTitle: "One step", verificationAccent: "closer.", verificationDescription: "Verified accounts keep your preparation history and route access secure.", verificationContinue: "Continue to login", verifying: "Verifying your email…", noVerificationToken: "No verification token was provided.", invalidVerification: "This verification link is invalid or expired.", unableConnect: "Unable to connect to the API." },
    about: { eyebrow: "About Drive Coach", title: "Prepare with", accent: "more clarity.", intro: "Drive Coach brings test-centre routes, key moments and practical preparation guidance together in one calm workspace.", approach: "Our approach", approachTitle: "Useful before test day.", bodyOne: "We design around the moments learner drivers need to understand: where to position, when to slow down, which signs deserve attention and how to practise consistently.", bodyTwo: "Route information is preparation material, not a promise of an examiner route. Road layouts, signs and traffic conditions can change, so drivers must always follow current rules and examiner instructions." },
    blog: { eyebrow: "Drive Coach guides", title: "Small lessons.", accent: "Better drives.", intro: "Clear, practical reading for the moments that deserve your attention before test day.", explore: "Explore preparation", guides: [{ tag: "ROUTE STUDY", title: "How to study a test route without memorising every street", text: "Focus on decision points, signs and positioning so your preparation remains useful when traffic changes." }, { tag: "ROUNDABOUTS", title: "A calmer way to approach difficult roundabouts", text: "Build a repeatable scan: signs, lane, mirrors, speed and exit. Practise the sequence before you practise the location." }, { tag: "PRACTICE", title: "What to record after every practice drive", text: "Use a short reflection to separate route-following progress from a formal assessment of driving skill." }] },
    contact: { eyebrow: "Contact", title: "We are here to", accent: "help you prepare.", intro: "Send us a question about an account, a route or your access period and we will point you in the right direction.", support: "SUPPORT", supportTitle: "Talk to Drive Coach", supportText: "For support and route-content questions, email our team. Include the centre and route name so we can investigate quickly.", email: "Email support", quickLinks: "QUICK LINKS", quickTitle: "Find your answer", quickText: "Browse the frequently asked questions or open the centre directory to start preparing.", faq: "Read the FAQ", centres: "Browse test centres" },
    account: { eyebrow: "Your Drive Coach space", title: "My account", description: "Keep your details, access and preparation plans in one place.", active: "Account active", verified: "Verified", created: "Account created", free: "Free", premium: "Premium", premiumActive: "Premium access is active.", freeDescription: "Browse centres and preview routes for free. Upgrade when you are ready for full route access.", premiumDescription: "Your premium preparation access is active.", validUntil: "Valid until", actions: "ACTIONS", billing: "BILLING", billingTitle: "Premium access", secureCheckout: "Secure checkout", billingIntro: "Unlock full route media and priority preparation features when live billing is connected.", choosePlan: "Choose plan", opening: "Opening…", noPlans: "No paid plans are configured yet.", paymentHistory: "PAYMENT HISTORY", invoices: "INVOICES" },
    dashboard: { eyebrow: "Your preparation space", title: "Keep moving", accent: "with confidence.", description: "Track the routes you have practised and focus on the skills that need another calm repetition.", explore: "Explore routes", smallHabits: "Small repetitions build calm habits.", access: "ACCESS", premiumActive: "Premium access is active.", freeActive: "Free access is active. Save routes and start building your practice history.", viewPlans: "View premium plans", manageAccount: "Manage account", attentionPoints: "attention points", noSaved: "No saved routes yet.", findCentre: "Find your test centre", reflect: "Reflect after every drive", complete: "complete", inProgress: "in progress", inbox: "INBOX", markRead: "Mark read" },
    route: { allCentres: "All test centres", routeExperience: "Route experience", updated: "Updated recently", preview: "Preview mode", sequence: "ROUTE SEQUENCE", mappedPreview: "Preview points will appear here when this route has been mapped.", openGoogle: "Open in Google Maps", selectedPoint: "SELECTED POINT", whatWatch: "What to watch", shown: "shown", fullRoute: "FULL ROUTE", previewPoints: "PREVIEW POINTS", unlockTitle: "Unlock the full route", unlockText: "See every point, image, warning and preparation note for this centre.", chooseAccess: "Choose access", unlocked: "Full route unlocked", unlockedText: "Your premium access includes all verified points and preparation details.", practiceRoutes: "Practice routes", keyPoints: "Key points", chooseRun: "Choose your practice run", around: "Routes around", freeRoute: "free route", premiumRoutes: "premium routes", routePreparing: "Route points are being prepared for this centre.", viewRoute: "View route", unlockRoute: "Unlock route", disclaimer: "Practice routes are designed to help you recognise likely road situations. Your official test route may be different.", previewNotConnected: "This route is a preview and is not connected to the database yet.", save: "Save route", saved: "Saved", completePractice: "Complete practice", startPractice: "Start practice", enableGps: "Enable optional GPS tracking", stopGps: "Stop GPS tracking", savedRoute: "Route saved to your dashboard.", removedRoute: "Route removed from saved routes.", updateSavedError: "Could not update saved routes.", sessionStarted: "Practice session started. Enable GPS to see your live position on the map.", startError: "Could not start practice session.", sessionCompleted: "Session completed. Complete this short reflection so Drive Coach can tailor your next route.", finishError: "Could not finish this session.", reflectionPrompt: "Your saved progress and reflection will appear in My dashboard.", locationUnsupported: "Location tracking is not supported by this browser.", permissionDenied: "Location permission was not granted.", gpsEnabled: "GPS tracking enabled. Your live practice position will appear on the map.", savedProgress: "Your saved progress and reflection will appear in My dashboard.", previewRoute: "Preview route", selectedPointFallback: "Selected point", practiceRouteLegend: "Practice route", attentionPoints: "Attention points" },
  },
  nl: {
    footer: { description: "Duidelijke routevoorbereiding voor rustigere en zelfverzekerdere examendagen.", testCentres: "Examencentra", guides: "Gidsen", contact: "Contact", privacy: "Privacy", terms: "Voorwaarden", copyright: "© 2026 Drive Coach", tagline: "Oefen met aandacht. Volg de weg voor je." },
    chatbot: { welcome: "Hoi, ik ben Drive Coach AI. Vraag me iets over je route, rotondes, observatie, snelheid of je voorbereiding op het examen.", quickLabel: "Probeer te vragen", quickPrompts: ["Hoe bereid ik me voor op mijn examen?", "Waar moet ik op letten bij rotondes?", "Hoe kan ik mijn observatie verbeteren?"], routeAware: "Routegerichte oefencoach", close: "AI-chat sluiten", open: "Drive Coach AI openen", placeholder: "Vraag iets over je oefenrit…", messageLabel: "Bericht aan Drive Coach AI", disclaimer: "AI-begeleiding is bedoeld voor oefenvoorbereiding. Volg altijd je instructeur en de actuele verkeersregels.", temporaryUnavailable: "De AI-coach is tijdelijk niet beschikbaar.", emptyAnswer: "Sorry, ik kan daar nu geen antwoord op geven." },
    auth: { backHome: "Terug naar home", prepareClarity: "Bereid je helder voor", storyTitle: "Voel je klaar", storyAccent: "voor je start.", storyDescription: "Bewaar je examencentra, houd je routes bij de hand en bouw vertrouwen op met elke oefenrit.", routeCount: "oefenroutes om te ontdekken", accountKicker: "DRIVE COACH-ACCOUNT", createTitle: "Maak je account aan", welcomeTitle: "Welkom terug", createDescription: "Bereid je met een gratis account voor op je examen.", loginDescription: "Log in om verder te oefenen.", fullName: "Volledige naam", yourName: "Jouw naam", email: "E-mailadres", emailPlaceholder: "jij@voorbeeld.be", password: "Wachtwoord", passwordPlaceholder: "Minstens 8 tekens", remember: "Onthoud mij", forgot: "Wachtwoord vergeten?", wait: "Even geduld…", createAccount: "Account aanmaken", login: "Inloggen", alreadyAccount: "Heb je al een account?", newToDriveCoach: "Nieuw bij Drive Coach?", termsNote: "Door verder te gaan ga je akkoord met onze voorwaarden en ons privacybeleid.", accountCreated: "Account aangemaakt. Je kunt nu inloggen.", genericError: "Er ging iets mis. Probeer het opnieuw.", apiError: "Kan geen verbinding maken met de API.", accountSecurity: "Accountbeveiliging", securityTitle: "Terug op de", securityAccent: "juiste route.", resetDescription: "Vraag een veilige link aan om je wachtwoord opnieuw in te stellen en ga verder wanneer je klaar bent.", resetTitle: "Wachtwoord opnieuw instellen", resetSubtitle: "Vul het e-mailadres van je account in.", sendReset: "Resetlink versturen", returnLogin: "Terug naar inloggen", localToken: "Token voor lokale ontwikkeling", continueReset: "Doorgaan met resetten", newPassword: "Nieuw wachtwoord", confirmPassword: "Wachtwoord bevestigen", resetPassword: "Wachtwoord resetten", passwordMismatch: "De wachtwoorden komen niet overeen.", invalidReset: "Ongeldige of verlopen resettoken.", verificationTitle: "Nog één stap", verificationAccent: "dichterbij.", verificationDescription: "Geverifieerde accounts houden je oefengeschiedenis en routetoegang veilig.", verificationContinue: "Doorgaan naar inloggen", verifying: "Je e-mailadres wordt gecontroleerd…", noVerificationToken: "Er is geen verificatietoken opgegeven.", invalidVerification: "Deze verificatielink is ongeldig of verlopen.", unableConnect: "Kan geen verbinding maken met de API." },
    about: { eyebrow: "Over Drive Coach", title: "Bereid je voor met", accent: "meer duidelijkheid.", intro: "Drive Coach brengt routes rond examencentra, belangrijke momenten en praktische voorbereiding samen in één rustige werkruimte.", approach: "Onze aanpak", approachTitle: "Nuttig vóór je examendag.", bodyOne: "We richten ons op de momenten die leerling-bestuurders moeten begrijpen: waar je positie kiest, wanneer je vertraagt, welke borden aandacht vragen en hoe je consequent oefent.", bodyTwo: "Route-informatie is voorbereidingsmateriaal en geen belofte van een examinatorroute. Wegen, borden en verkeerssituaties kunnen veranderen. Volg daarom altijd de actuele regels en instructies van de examinator." },
    blog: { eyebrow: "Drive Coach-gidsen", title: "Kleine lessen.", accent: "Betere ritten.", intro: "Duidelijke, praktische artikels over de momenten die vóór je examendag je aandacht verdienen.", explore: "Ontdek de voorbereiding", guides: [{ tag: "ROUTE STUDEREN", title: "Een examenroute bestuderen zonder elke straat uit het hoofd te leren", text: "Focus op beslispunten, borden en positie, zodat je voorbereiding nuttig blijft wanneer het verkeer verandert." }, { tag: "ROTONDES", title: "Een rustigere aanpak voor moeilijke rotondes", text: "Bouw een vaste scan op: borden, rijstrook, spiegels, snelheid en uitrit. Oefen de volgorde vóór je de locatie oefent." }, { tag: "OEFENEN", title: "Wat je na elke oefenrit kunt noteren", text: "Gebruik een korte reflectie om routekennis te onderscheiden van een formele beoordeling van je rijvaardigheid." }] },
    contact: { eyebrow: "Contact", title: "We helpen je graag", accent: "voorbereiden.", intro: "Stuur ons een vraag over je account, een route of je toegangsperiode. We wijzen je naar de juiste oplossing.", support: "ONDERSTEUNING", supportTitle: "Praat met Drive Coach", supportText: "Voor vragen over ondersteuning of route-inhoud kun je ons mailen. Vermeld het centrum en de routenaam, zodat we snel kunnen helpen.", email: "Ondersteuning mailen", quickLinks: "SNELLE LINKS", quickTitle: "Vind je antwoord", quickText: "Bekijk de veelgestelde vragen of open de lijst met examencentra om te beginnen.", faq: "Bekijk de FAQ", centres: "Bekijk examencentra" },
    account: { eyebrow: "Jouw Drive Coach-ruimte", title: "Mijn account", description: "Bewaar je gegevens, toegang en voorbereidingsplannen op één plek.", active: "Account actief", verified: "Geverifieerd", created: "Account aangemaakt", free: "Gratis", premium: "Premium", premiumActive: "Je premiumvoorbereiding is actief.", freeDescription: "Bekijk examencentra en routes gratis. Upgrade wanneer je klaar bent voor volledige toegang.", premiumDescription: "Je premiumvoorbereiding is actief.", validUntil: "Geldig tot", actions: "ACTIES", billing: "FACTURATIE", billingTitle: "Premiumtoegang", secureCheckout: "Veilige checkout", billingIntro: "Ontgrendel alle route-media en prioritaire voorbereiding zodra live facturatie is verbonden.", choosePlan: "Kies pakket", opening: "Openen…", noPlans: "Er zijn nog geen betaalde pakketten ingesteld.", paymentHistory: "BETALINGSGESCHIEDENIS", invoices: "FACTUREN" },
    dashboard: { eyebrow: "Jouw voorbereidingsruimte", title: "Blijf vooruitgaan", accent: "met vertrouwen.", description: "Volg de routes die je hebt geoefend en focus op vaardigheden die nog een rustige herhaling nodig hebben.", explore: "Routes bekijken", smallHabits: "Kleine herhalingen bouwen rustige gewoontes.", access: "TOEGANG", premiumActive: "Premiumtoegang is actief.", freeActive: "Gratis toegang is actief. Bewaar routes en bouw je oefengeschiedenis op.", viewPlans: "Premium pakketten bekijken", manageAccount: "Account beheren", attentionPoints: "aandachtspunten", noSaved: "Nog geen opgeslagen routes.", findCentre: "Vind je examencentrum", reflect: "Reflecteer na elke rit", complete: "voltooid", inProgress: "bezig", inbox: "INBOX", markRead: "Markeren als gelezen" },
    route: { allCentres: "Alle examencentra", routeExperience: "Route-ervaring", updated: "Onlangs bijgewerkt", preview: "Voorbeeldmodus", sequence: "ROUTEVOLGORDE", mappedPreview: "De routepunten verschijnen hier zodra deze route in kaart is gebracht.", openGoogle: "Openen in Google Maps", selectedPoint: "GESELECTEERD PUNT", whatWatch: "Waar let je op?", shown: "getoond", fullRoute: "VOLLEDIGE ROUTE", previewPoints: "VOORBEELDPUNTEN", unlockTitle: "Ontgrendel de volledige route", unlockText: "Bekijk elk punt, beeld, waarschuwing en voorbereidingsadvies voor dit centrum.", chooseAccess: "Kies toegang", unlocked: "Volledige route ontgrendeld", unlockedText: "Je premiumtoegang bevat alle geverifieerde punten en voorbereidingsdetails.", practiceRoutes: "Oefenroutes", keyPoints: "Aandachtspunten", chooseRun: "Kies je oefenrit", around: "Routes rond", freeRoute: "gratis route", premiumRoutes: "premiumroutes", routePreparing: "De routepunten voor dit centrum worden voorbereid.", viewRoute: "Route bekijken", unlockRoute: "Route ontgrendelen", disclaimer: "Oefenroutes helpen je om waarschijnlijke verkeerssituaties te herkennen. Je officiële examenroute kan anders zijn.", previewNotConnected: "Deze route is een voorbeeld en is nog niet verbonden met de database.", save: "Route opslaan", saved: "Opgeslagen", completePractice: "Oefenrit voltooien", startPractice: "Oefenrit starten", enableGps: "Optionele GPS-tracking inschakelen", stopGps: "GPS-tracking stoppen", savedRoute: "Route opgeslagen in je dashboard.", removedRoute: "Route verwijderd uit je opgeslagen routes.", updateSavedError: "Opgeslagen routes konden niet worden bijgewerkt.", sessionStarted: "Oefenrit gestart. Schakel GPS in om je live positie op de kaart te zien.", startError: "De oefenrit kon niet worden gestart.", sessionCompleted: "Oefenrit voltooid. Vul deze korte reflectie in zodat Drive Coach je volgende route kan afstemmen.", finishError: "Deze oefenrit kon niet worden voltooid.", reflectionPrompt: "Je opgeslagen voortgang en reflectie verschijnen in Mijn dashboard.", locationUnsupported: "Locatietracking wordt niet ondersteund door deze browser.", permissionDenied: "Locatietoestemming is niet gegeven.", gpsEnabled: "GPS-tracking ingeschakeld. Je live oefenpositie verschijnt op de kaart.", savedProgress: "Je opgeslagen voortgang en reflectie verschijnen in Mijn dashboard.", previewRoute: "Voorbeeldroute", selectedPointFallback: "Geselecteerd punt", practiceRouteLegend: "Oefenroute", attentionPoints: "Aandachtspunten" },
  },
};
