"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { isLocale, type Locale } from "../../lib/i18n";
import { useSiteCopy } from "../../lib/useLocale";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";
type Localized = { en: string; nl: string };
type Category = { id: string; label: Localized; details: Array<{ id: string; label: Localized }> };
type Reflection = { overallFeeling: string; difficultyCategories: string[]; difficultyDetails: Record<string, string[]>; instructorFeedback: boolean; instructorCategories: string[]; instructorNotes: string };

const feelings = [
  { id: "very_good", emoji: "😄", label: { en: "Very good", nl: "Heel goed" } },
  { id: "good", emoji: "🙂", label: { en: "Good", nl: "Goed" } },
  { id: "okay", emoji: "😐", label: { en: "Fair", nl: "Redelijk" } },
  { id: "difficult", emoji: "😕", label: { en: "Difficult", nl: "Moeilijk" } },
  { id: "very_difficult", emoji: "😣", label: { en: "Very difficult", nl: "Heel moeilijk" } },
];

const categories: Category[] = [
  { id: "speed", label: { en: "Speed", nl: "Snelheid" }, details: [{ id: "speed_limit_missed", label: { en: "Missed a speed limit", nl: "Snelheidslimiet gemist" } }, { id: "speed_limit_uncertain", label: { en: "Unsure about the speed limit", nl: "Onzeker over de snelheidslimiet" } }, { id: "too_fast", label: { en: "Drove too fast", nl: "Te snel gereden" } }, { id: "too_slow", label: { en: "Drove unnecessarily slowly", nl: "Onnodig traag gereden" } }, { id: "late_adjustment", label: { en: "Adjusted speed too late", nl: "Te laat snelheid aangepast" } }, { id: "bends_junctions", label: { en: "Speed at bends or junctions", nl: "Snelheid bij bochten of kruispunten" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "priority", label: { en: "Right of way", nl: "Voorrang" }, details: [{ id: "priority_uncertain", label: { en: "Unsure who had priority", nl: "Onzeker over voorrang" } }, { id: "priority_sign", label: { en: "Missed a priority sign", nl: "Voorrangsbord gemist" } }, { id: "stop_yield", label: { en: "Stop or give-way approach", nl: "Stoppen of voorrang verlenen" } }, { id: "timing", label: { en: "Timing at the junction", nl: "Timing bij het kruispunt" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "roundabouts", label: { en: "Roundabouts", nl: "Rotondes" }, details: [{ id: "wrong_lane", label: { en: "Choosing the correct lane", nl: "Juiste rijstrook kiezen" } }, { id: "late_lane_change", label: { en: "Changed lanes too late", nl: "Te laat van rijstrook gewisseld" } }, { id: "approach_speed", label: { en: "Speed on approach", nl: "Snelheid bij het naderen" } }, { id: "observation", label: { en: "Looking and observing", nl: "Kijken / observeren" } }, { id: "mirrors", label: { en: "Mirrors or blind spot", nl: "Spiegels of dode hoek" } }, { id: "priority", label: { en: "Unsure about right of way", nl: "Onzeker over voorrang" } }, { id: "exit_preparation", label: { en: "Preparing the exit", nl: "Uitrit voorbereiden" } }, { id: "cyclists_pedestrians", label: { en: "Cyclists or pedestrians", nl: "Fietsers of voetgangers" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "junctions", label: { en: "Junctions", nl: "Kruispunten" }, details: [{ id: "approach", label: { en: "Approach and positioning", nl: "Naderen en positioneren" } }, { id: "observation", label: { en: "Looking and observing", nl: "Kijken / observeren" } }, { id: "priority", label: { en: "Right of way", nl: "Voorrang" } }, { id: "lights", label: { en: "Traffic lights", nl: "Verkeerslichten" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "lanes", label: { en: "Lanes and lane choice", nl: "Rijstroken & rijstrookkeuze" }, details: [{ id: "lane_choice", label: { en: "Choosing the correct lane", nl: "Juiste rijstrook kiezen" } }, { id: "late_change", label: { en: "Changing lanes too late", nl: "Te laat van rijstrook gewisseld" } }, { id: "mirrors_blind_spot", label: { en: "Mirrors or blind spot", nl: "Spiegels of dode hoek" } }, { id: "signal", label: { en: "Signalling", nl: "Richting aangeven" } }, { id: "road_markings", label: { en: "Road markings", nl: "Wegmarkeringen" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "observation", label: { en: "Looking, mirrors and blind spot", nl: "Kijken, spiegels & dode hoek" }, details: [{ id: "mirrors", label: { en: "Mirror checks", nl: "Spiegels controleren" } }, { id: "blind_spot", label: { en: "Blind-spot checks", nl: "Dode hoek controleren" } }, { id: "look_ahead", label: { en: "Looking far enough ahead", nl: "Ver genoeg vooruit kijken" } }, { id: "cyclists", label: { en: "Spotting cyclists", nl: "Fietsers opmerken" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "signs", label: { en: "Traffic signs and lights", nl: "Verkeersborden & verkeerslichten" }, details: [{ id: "missed_sign", label: { en: "Missed a sign", nl: "Verkeersbord gemist" } }, { id: "uncertain_sign", label: { en: "Unsure about a sign", nl: "Onzeker over een verkeersbord" } }, { id: "traffic_lights", label: { en: "Traffic lights", nl: "Verkeerslichten" } }, { id: "road_markings", label: { en: "Road markings", nl: "Wegmarkeringen" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "vulnerable", label: { en: "Cyclists and pedestrians", nl: "Fietsers & voetgangers" }, details: [{ id: "cyclists", label: { en: "Cyclists", nl: "Fietsers" } }, { id: "pedestrians", label: { en: "Pedestrians", nl: "Voetgangers" } }, { id: "crossings", label: { en: "Crossings", nl: "Oversteekplaatsen" } }, { id: "safe_distance", label: { en: "Keeping safe distance", nl: "Veilige afstand houden" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "merging", label: { en: "Merging and overtaking", nl: "Invoegen & inhalen" }, details: [{ id: "safe_gap", label: { en: "Finding a safe gap", nl: "Veilige ruimte vinden" } }, { id: "mirrors", label: { en: "Mirrors or blind spot", nl: "Spiegels of dode hoek" } }, { id: "speed", label: { en: "Matching speed", nl: "Snelheid aanpassen" } }, { id: "position", label: { en: "Positioning", nl: "Positioneren" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "distance", label: { en: "Distance and anticipation", nl: "Afstand & anticiperen" }, details: [{ id: "following_distance", label: { en: "Following distance", nl: "Volgafstand" } }, { id: "side_distance", label: { en: "Side distance", nl: "Zijdelingse afstand" } }, { id: "anticipation", label: { en: "Anticipating traffic", nl: "Vooruitkijken en anticiperen" } }, { id: "braking", label: { en: "Braking in time", nl: "Op tijd remmen" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "control", label: { en: "Vehicle control", nl: "Voertuigbeheersing" }, details: [{ id: "braking", label: { en: "Smooth braking", nl: "Vlot remmen" } }, { id: "steering", label: { en: "Steering", nl: "Sturen" } }, { id: "clutch_gears", label: { en: "Clutch or gears", nl: "Koppeling of versnellingen" } }, { id: "starts_stops", label: { en: "Starting and stopping", nl: "Starten en stoppen" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "manoeuvres", label: { en: "Manoeuvres", nl: "Manoeuvres" }, details: [{ id: "parking", label: { en: "Parking", nl: "Parkeren" } }, { id: "reversing", label: { en: "Reversing", nl: "Achteruitrijden" } }, { id: "turning", label: { en: "Turning", nl: "Draaien" } }, { id: "observation", label: { en: "Observation", nl: "Observeren" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "navigation", label: { en: "Navigation / GPS", nl: "Navigatie / GPS" }, details: [{ id: "missed_instruction", label: { en: "Missed an instruction", nl: "Instructie gemist" } }, { id: "gps_confusion", label: { en: "Confusion using GPS", nl: "Onzekerheid met GPS" } }, { id: "route_choice", label: { en: "Route choice", nl: "Routekeuze" } }, { id: "signs", label: { en: "Following signs", nl: "Verkeersborden volgen" } }, { id: "other", label: { en: "Other", nl: "Anders" } }] },
  { id: "other", label: { en: "Other", nl: "Anders" }, details: [{ id: "other", label: { en: "Other", nl: "Anders" } }] },
];

const emptyReflection: Reflection = { overallFeeling: "", difficultyCategories: [], difficultyDetails: {}, instructorFeedback: false, instructorCategories: [], instructorNotes: "" };
const ui = {
  en: { heading: "How did your practice drive go?", intro: "Choose what best matches your drive.", step: "Step", of: "of", next: "Next", back: "Back", skip: "Skip", save: "Save reflection", saving: "Saving…", difficultyHeading: "What did you find difficult?", chooseMultiple: "You can choose multiple options.", noProblems: "No problems", instructorHeading: "Did you receive feedback from your instructor or supervisor?", feedbackAbout: "What was the feedback about?", extraNote: "Extra note from your instructor (optional)", notePlaceholder: "Write an optional note…", saved: "Reflection saved. Your next approved route will focus on the areas you flagged.", skipped: "Reflection skipped. You can add feedback after another practice drive.", reflectionIntro: "Your answers help Drive Coach tailor your next practice route.", yes: "Yes", no: "No", detailsFor: "What did you find difficult with", instructorCategories: "Choose the feedback categories." },
  nl: { heading: "Hoe ging je oefenrit?", intro: "Kies wat het beste bij je rit past.", step: "Scherm", of: "van", next: "Volgende", back: "Terug", skip: "Overslaan", save: "Reflectie opslaan", saving: "Opslaan…", difficultyHeading: "Waar had je tijdens deze rit moeite mee?", chooseMultiple: "Je kunt meerdere opties kiezen.", noProblems: "Geen problemen", instructorHeading: "Heb je feedback gekregen van je instructeur of begeleider?", feedbackAbout: "Waar ging de feedback over?", extraNote: "Extra opmerking van je instructeur (optioneel)", notePlaceholder: "Schrijf een optionele opmerking…", saved: "Reflectie opgeslagen. Drive Coach stemt je volgende route af op je aandachtspunten.", skipped: "Reflectie overgeslagen. Je kunt na een volgende oefenrit feedback toevoegen.", reflectionIntro: "Met je antwoorden kan Drive Coach je volgende oefenroute beter afstemmen.", yes: "Ja", no: "Nee", detailsFor: "Wat vond je moeilijk bij", instructorCategories: "Kies de feedbackcategorieën." },
} as const;

type Props = { routeId?: string; routeSlug: string; onPositionUpdate?: (position: GeolocationPosition) => void; onTrackingChange?: (tracking: boolean) => void; onPracticeStart?: () => void };

export default function PracticeControls({ routeId, routeSlug, onPositionUpdate, onTrackingChange, onPracticeStart }: Props) {
  const router = useRouter();
  const [favorite, setFavorite] = useState(false); const [sessionId, setSessionId] = useState<string | null>(null); const [completedSession, setCompletedSession] = useState(false); const [reflectionStep, setReflectionStep] = useState(1); const [reflection, setReflection] = useState<Reflection>(emptyReflection); const [tracking, setTracking] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [locale, setLocale] = useState<Locale>("en"); const watchRef = useRef<number | null>(null);
  const copy = ui[locale];
  const site = useSiteCopy();
  const routeCopy = site.route;

  useEffect(() => { const sync = () => { const stored = window.localStorage.getItem("routepilot.locale"); if (isLocale(stored)) setLocale(stored); }; sync(); window.addEventListener("routepilot-locale-change", sync); return () => window.removeEventListener("routepilot-locale-change", sync); }, []);
  useEffect(() => { const token = window.sessionStorage.getItem("routepilot.accessToken"); if (!token || !routeId) return; fetch(`${API}/me/favorites`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) return; const items = await response.json() as Array<{ routeId: string }>; setFavorite(items.some((item) => item.routeId === routeId)); }).catch(() => undefined); }, [routeId]);
  useEffect(() => () => { if (watchRef.current !== null) navigator.geolocation?.clearWatch(watchRef.current); }, []);

  function requireRoute() { if (!routeId) { setMessage(routeCopy.previewNotConnected); return false; } if (!window.sessionStorage.getItem("routepilot.accessToken")) { router.push("/auth/login"); return false; } return true; }
  async function toggleFavorite() { if (!requireRoute()) return; setBusy(true); setMessage(""); const token = window.sessionStorage.getItem("routepilot.accessToken"); const response = await fetch(`${API}/me/favorites/${routeId}`, { method: favorite ? "DELETE" : "POST", headers: { Authorization: `Bearer ${token}` } }).catch(() => null); setBusy(false); if (!response?.ok) { setMessage(routeCopy.updateSavedError); return; } setFavorite(!favorite); setMessage(!favorite ? routeCopy.savedRoute : routeCopy.removedRoute); }
  async function startPractice() { if (!requireRoute()) return; setBusy(true); setMessage(""); const token = window.sessionStorage.getItem("routepilot.accessToken"); const response = await fetch(`${API}/practice-sessions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ routeId }) }).catch(() => null); const payload = await response?.json().catch(() => null); setBusy(false); if (!response?.ok || !payload?.id) { setMessage(payload?.message ?? routeCopy.startError); return; } onPracticeStart?.(); setSessionId(payload.id); setCompletedSession(false); setReflectionStep(1); setReflection(emptyReflection); startTracking(payload.id); }
  async function completePractice() { if (!sessionId) return; stopTracking(); setBusy(true); const token = window.sessionStorage.getItem("routepilot.accessToken"); const response = await fetch(`${API}/practice-sessions/${sessionId}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ completionPct: 100, complete: true }) }).catch(() => null); setBusy(false); if (!response?.ok) { setMessage(routeCopy.finishError); return; } setCompletedSession(true); setReflectionStep(1); setReflection(emptyReflection); setMessage(routeCopy.sessionCompleted); }
  async function saveReflection() { if (!sessionId) return; setBusy(true); setMessage(""); const token = window.sessionStorage.getItem("routepilot.accessToken"); const categoriesSelected = new Set(reflection.difficultyCategories); const detailsText = JSON.stringify(reflection.difficultyDetails).toLowerCase(); const low = (selected: boolean) => selected ? 2 : undefined; const response = await fetch(`${API}/practice-sessions/${sessionId}/reflection`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ overallFeeling: reflection.overallFeeling || undefined, difficultyCategories: reflection.difficultyCategories, difficultyDetails: reflection.difficultyDetails, instructorFeedback: reflection.instructorFeedback, instructorCategories: reflection.instructorCategories, instructorNotes: reflection.instructorNotes || undefined, speedCompliance: low(categoriesSelected.has("speed")), rightOfWayConfidence: low(categoriesSelected.has("priority")), roundaboutConfidence: low(categoriesSelected.has("roundabouts")), laneChangeConfidence: low(categoriesSelected.has("lanes")), flaggedSpeeding: detailsText.includes("too_fast"), missedRightOfWay: categoriesSelected.has("priority") }) }).catch(() => null); const payload = await response?.json().catch(() => null); setBusy(false); if (!response?.ok) { setMessage(payload?.message ?? (locale === "nl" ? "Je reflectie kon niet worden opgeslagen." : "Could not save your reflection.")); return; } setSessionId(null); setCompletedSession(false); setReflection(emptyReflection); setReflectionStep(1); setMessage(copy.saved); }
  function skipReflection() { setSessionId(null); setCompletedSession(false); setReflection(emptyReflection); setReflectionStep(1); setMessage(copy.skipped); }
  function startTracking(activeSessionId = sessionId) { if (!activeSessionId || !navigator.geolocation) { setMessage(routeCopy.locationUnsupported); return; } if (watchRef.current !== null) return; const token = window.sessionStorage.getItem("routepilot.accessToken"); if (!token) return; const onPosition = (position: GeolocationPosition) => { onPositionUpdate?.(position); void fetch(`${API}/practice-sessions/${activeSessionId}/track`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyM: position.coords.accuracy, speedKph: position.coords.speed === null ? undefined : position.coords.speed * 3.6 }) }).catch(() => undefined); }; const onError = () => { if (watchRef.current !== null) navigator.geolocation.clearWatch(watchRef.current); watchRef.current = null; setTracking(false); onTrackingChange?.(false); setMessage(routeCopy.permissionDenied); }; watchRef.current = navigator.geolocation.watchPosition(onPosition, onError, { enableHighAccuracy: true, maximumAge: 5000, timeout: 15000 }); setTracking(true); onTrackingChange?.(true); setMessage(routeCopy.gpsEnabled); }
  function stopTracking() { if (watchRef.current !== null) navigator.geolocation?.clearWatch(watchRef.current); watchRef.current = null; setTracking(false); onTrackingChange?.(false); }
  function toggleCategory(id: string, target: "difficultyCategories" | "instructorCategories") { setReflection((current) => { const list = current[target].includes(id) ? current[target].filter((item) => item !== id) : [...current[target], id]; const details = target === "difficultyCategories" ? { ...current.difficultyDetails } : current.difficultyDetails; if (target === "difficultyCategories" && !list.includes(id)) delete details[id]; return { ...current, [target]: list, difficultyDetails: details }; }); }
  function toggleDetail(categoryId: string, detailId: string) { setReflection((current) => { const selected = current.difficultyDetails[categoryId] ?? []; const next = selected.includes(detailId) ? selected.filter((item) => item !== detailId) : [...selected, detailId]; return { ...current, difficultyDetails: { ...current.difficultyDetails, [categoryId]: next } }; }); }
  function label(item: Localized) { return item[locale]; }
  const selectedCategories = categories.filter((category) => reflection.difficultyCategories.includes(category.id));
  const stepTitle = reflectionStep === 1 ? copy.heading : reflectionStep === 2 ? copy.difficultyHeading : reflectionStep === 3 ? copy.detailsFor : copy.instructorHeading;

  return <div className="practice-controls"><div className="practice-control-actions"><button className={`save-route-button ${favorite ? "is-saved" : ""}`} onClick={() => void toggleFavorite()} disabled={busy}><span>{favorite ? "♥" : "♡"}</span>{favorite ? routeCopy.saved : routeCopy.save}</button>{completedSession ? <button className="start-practice-button is-active" onClick={() => void saveReflection()} disabled={busy}>{copy.save} <span>✓</span></button> : sessionId ? <button className="start-practice-button is-active" onClick={() => void completePractice()} disabled={busy}>{routeCopy.completePractice} <span>✓</span></button> : <button className="start-practice-button" onClick={() => void startPractice()} disabled={busy}>{routeCopy.startPractice} <span>↗</span></button>}</div>
    {sessionId && !completedSession && <button className={`gps-button ${tracking ? "is-tracking" : ""}`} onClick={() => tracking ? stopTracking() : startTracking()}>{tracking ? routeCopy.stopGps : routeCopy.enableGps} <span>⌖</span></button>}
    {completedSession && <div className="reflection-form"><div className="reflection-heading"><strong>{stepTitle}</strong><small>{copy.reflectionIntro}</small></div><div className="reflection-progress"><span style={{ width: `${reflectionStep * 25}%` }} /><small>{copy.step} {reflectionStep} {copy.of} 4</small></div>
      {reflectionStep === 1 && <><p className="reflection-question-copy">{copy.intro}</p><div className="reflection-choice-grid">{feelings.map((feeling) => <button type="button" className={`reflection-choice ${reflection.overallFeeling === feeling.id ? "is-selected" : ""}`} key={feeling.id} onClick={() => setReflection((current) => ({ ...current, overallFeeling: feeling.id }))}><span>{feeling.emoji}</span><strong>{label(feeling.label)}</strong></button>)}</div><div className="reflection-footer"><button type="button" className="reflection-text-button" onClick={skipReflection}>{copy.skip}</button><button type="button" className="reflection-next-button" disabled={!reflection.overallFeeling} onClick={() => setReflectionStep(2)}>{copy.next} →</button></div></>}
      {reflectionStep === 2 && <><p className="reflection-question-copy">{copy.chooseMultiple}</p><div className="reflection-option-grid">{categories.map((category) => <button type="button" className={`reflection-option ${reflection.difficultyCategories.includes(category.id) ? "is-selected" : ""}`} key={category.id} onClick={() => toggleCategory(category.id, "difficultyCategories")}><span>{reflection.difficultyCategories.includes(category.id) ? "✓" : ""}</span>{label(category.label)}</button>)}</div><div className="reflection-footer"><button type="button" className="reflection-text-button" onClick={() => setReflectionStep(1)}>{copy.back}</button><button type="button" className="reflection-no-problems" onClick={() => { setReflection((current) => ({ ...current, difficultyCategories: [], difficultyDetails: {} })); setReflectionStep(4); }}>{copy.noProblems}</button><button type="button" className="reflection-next-button" onClick={() => setReflectionStep(reflection.difficultyCategories.length ? 3 : 4)}>{copy.next} →</button></div></>}
      {reflectionStep === 3 && <><p className="reflection-question-copy">{copy.chooseMultiple}</p><div className="reflection-detail-list">{selectedCategories.map((category) => <section className="reflection-detail-group" key={category.id}><h4>{copy.detailsFor} {label(category.label).toLowerCase()}?</h4><div className="reflection-option-grid">{category.details.map((detail) => <button type="button" className={`reflection-option ${reflection.difficultyDetails[category.id]?.includes(detail.id) ? "is-selected" : ""}`} key={detail.id} onClick={() => toggleDetail(category.id, detail.id)}><span>{reflection.difficultyDetails[category.id]?.includes(detail.id) ? "✓" : ""}</span>{label(detail.label)}</button>)}</div></section>)}</div><div className="reflection-footer"><button type="button" className="reflection-text-button" onClick={() => setReflectionStep(2)}>{copy.back}</button><button type="button" className="reflection-next-button" onClick={() => setReflectionStep(4)}>{copy.next} →</button></div></>}
      {reflectionStep === 4 && <><div className="reflection-question-block"><h4>{copy.instructorHeading}</h4><div className="reflection-choice-row"><button type="button" className={`reflection-choice-small ${reflection.instructorFeedback ? "is-selected" : ""}`} onClick={() => setReflection((current) => ({ ...current, instructorFeedback: true }))}>{copy.yes}</button><button type="button" className={`reflection-choice-small ${!reflection.instructorFeedback ? "is-selected" : ""}`} onClick={() => setReflection((current) => ({ ...current, instructorFeedback: false, instructorCategories: [] }))}>{copy.no}</button></div></div>{reflection.instructorFeedback && <div className="reflection-detail-group"><h4>{copy.feedbackAbout}</h4><p className="reflection-question-copy">{copy.instructorCategories}</p><div className="reflection-option-grid">{categories.map((category) => <button type="button" className={`reflection-option ${reflection.instructorCategories.includes(category.id) ? "is-selected" : ""}`} key={category.id} onClick={() => toggleCategory(category.id, "instructorCategories")}><span>{reflection.instructorCategories.includes(category.id) ? "✓" : ""}</span>{label(category.label)}</button>)}</div></div>}<label className="reflection-note-label">{copy.extraNote}<textarea maxLength={2000} placeholder={copy.notePlaceholder} value={reflection.instructorNotes} onChange={(event) => setReflection((current) => ({ ...current, instructorNotes: event.target.value }))} /></label><div className="reflection-footer"><button type="button" className="reflection-text-button" onClick={() => setReflectionStep(selectedCategories.length ? 3 : 2)}>{copy.back}</button><button type="button" className="reflection-next-button" onClick={() => void saveReflection()} disabled={busy}>{busy ? copy.saving : copy.save} ✓</button></div></>}
    </div>}
    {message && <p className="practice-message">{message}</p>}<small className="practice-route-label">{routeId ? routeCopy.savedProgress : `${routeCopy.previewRoute} · ${routeSlug}`}</small>
  </div>;
}
