"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";
type CoachData = { focus: { skill: string; message: string }; checklist: Array<{ sequence: number; title: string; instruction: string }>; safety: string };
type Recommendation = { focus: { skill: string; message: string }; route: { slug: string; name: string; centreName: string; durationMin: number | null; pointCount: number } | null; reason: string; safety: string };
type DriveCoachData = { focus: { skill: string; message: string }; weaknesses: Array<{ code: string; label: string; occurrenceCount: number }>; tips: Array<{ code: string; voiceTextEn: string; skillName: string }>; safety: string };

export default function RouteCoach({ routeId }: { routeId?: string }) {
  const router = useRouter(); const [data, setData] = useState<CoachData | null>(null); const [recommendation, setRecommendation] = useState<Recommendation | null>(null); const [driveCoach, setDriveCoach] = useState<DriveCoachData | null>(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [speaking, setSpeaking] = useState(false);
  async function load() { if (!routeId) { setError("This preview is not connected to a published route."); return; } const token = window.sessionStorage.getItem("routepilot.accessToken"); if (!token) { router.push("/auth/login"); return; } setLoading(true); setError(""); try { const headers = { Authorization: `Bearer ${token}` }; const [coachResponse, recommendationResponse, driveCoachResponse] = await Promise.all([fetch(`${API}/me/route-assistant?routeId=${encodeURIComponent(routeId)}`, { headers }), fetch(`${API}/me/route-recommendation?routeId=${encodeURIComponent(routeId)}`, { headers }), fetch(`${API}/me/drive-coach?routeId=${encodeURIComponent(routeId)}`, { headers })]); const payload = await coachResponse.json().catch(() => ({})); const recommendationPayload = await recommendationResponse.json().catch(() => null); const driveCoachPayload = await driveCoachResponse.json().catch(() => null); if (!coachResponse.ok) throw new Error(payload.message ?? "Unable to load route coach."); setData(payload as CoachData); if (recommendationResponse.ok) setRecommendation(recommendationPayload as Recommendation); if (driveCoachResponse.ok) setDriveCoach(driveCoachPayload as DriveCoachData); setOpen(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load route coach."); } finally { setLoading(false); } }
  function speak() { if (!data || !("speechSynthesis" in window)) { setError("Voice guidance is not supported by this browser."); return; } if (speaking) { window.speechSynthesis.cancel(); setSpeaking(false); return; } const text = `${data.focus.skill}. ${data.focus.message} ${data.checklist.map((item) => `${item.sequence}. ${item.title}. ${item.instruction}`).join(" ")}`; const utterance = new SpeechSynthesisUtterance(text); utterance.rate = 0.92; utterance.onend = () => setSpeaking(false); window.speechSynthesis.speak(utterance); setSpeaking(true); }
  useEffect(() => () => { if ("speechSynthesis" in window) window.speechSynthesis.cancel(); }, []);
  return <section className={`route-coach ${open ? "is-open" : ""}`}><div className="route-coach-header"><div><span className="small-label">GROUNDED ROUTE COACH</span><strong>Prepare with focus</strong></div><span className="coach-spark">✦</span></div>{!open ? <button className="route-coach-load" onClick={() => void load()} disabled={loading}>{loading ? "Preparing your guidance…" : "Build my route checklist ↗"}</button> : <><div className="coach-focus"><span>FOCUS · {driveCoach?.focus.skill ?? data?.focus.skill}</span><p>{driveCoach?.focus.message ?? data?.focus.message}</p></div>{driveCoach?.weaknesses?.length ? <div className="coach-recommendation"><span>RECENT FOCUS AREAS</span>{driveCoach.weaknesses.slice(0, 3).map((weakness) => <p key={weakness.code}><strong>{weakness.label}</strong><small>Reported {weakness.occurrenceCount}×</small></p>)}</div> : null}<div className="coach-checklist">{data?.checklist.slice(0, 5).map((item) => <div key={item.sequence}><b>{String(item.sequence).padStart(2, "0")}</b><span><strong>{item.title}</strong><small>{item.instruction}</small></span></div>)}</div>{driveCoach?.tips?.length ? <div className="coach-recommendation"><span>VERIFIED COACHING TIP</span><p>{driveCoach.tips[0].voiceTextEn}</p></div> : null}{recommendation && <div className="coach-recommendation"><span>NEXT APPROVED ROUTE</span>{recommendation.route ? <a href={`/routes/${recommendation.route.slug}`}><strong>{recommendation.route.name}</strong><small>{recommendation.reason} · {recommendation.route.pointCount} points</small></a> : <p>{recommendation.reason}</p>}</div>}<div className="coach-actions"><button onClick={speak}>{speaking ? "Stop voice" : "Read guidance aloud"} <span>{speaking ? "■" : "◖"}</span></button><button onClick={() => setOpen(false)} aria-label="Close route coach">×</button></div><small className="coach-safety">{data?.safety} {recommendation?.safety} {driveCoach?.safety}</small></>}{error && <p className="practice-message">{error}</p>}</section>;
}
