"use client";

import { FormEvent, useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";
type BusinessData = { instructor: { schoolId: string; schoolName: string; schoolSlug: string; status: string } | null; enrollments: Array<{ id: string; status: string; studentEmail: string; studentName: string | null }>; studentEnrollments: Array<{ id: string; status: string; schoolName: string; instructorEmail: string; instructorName: string | null }> };
type Referral = { id: string; code: string; schoolId?: string | null; commissionBps: number; referralCount: number; commissionCents: number; active: boolean; createdAt?: string };

export default function PartnershipPanel() {
  const [business, setBusiness] = useState<BusinessData | null>(null); const [referrals, setReferrals] = useState<Referral[]>([]); const [monthlyCode, setMonthlyCode] = useState(""); const [school, setSchool] = useState({ name: "", slug: "", email: "" }); const [studentEmail, setStudentEmail] = useState(""); const [code, setCode] = useState(""); const [claimCode, setClaimCode] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const token = () => window.sessionStorage.getItem("routepilot.accessToken") || "";
  async function load() { const accessToken = token(); if (!accessToken) return; const headers = { Authorization: `Bearer ${accessToken}` }; const [businessResponse, referralResponse] = await Promise.all([fetch(`${API}/b2b/me`, { headers }), fetch(`${API}/me/referrals`, { headers })]); if (businessResponse.ok) { const data = await businessResponse.json() as BusinessData; setBusiness(data); if (data.instructor?.schoolId) { const codeResponse = await fetch(`${API}/referrals/schools/${data.instructor.schoolId}/current`, { headers }); if (codeResponse.ok) setMonthlyCode((await codeResponse.json() as { code: string }).code); } } if (referralResponse.ok) setReferrals(await referralResponse.json() as Referral[]); }
  useEffect(() => { void load(); }, []);
  async function submit(path: string, body: unknown, success: string) { setBusy(true); setMessage(""); const response = await fetch(`${API}${path}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setMessage(payload?.message ?? "Could not update the partnership workspace."); return false; } setMessage(success); await load(); return true; }
  async function createSchool(event: FormEvent) { event.preventDefault(); if (await submit("/b2b/schools", { ...school, email: school.email || undefined }, "Driving school workspace created.")) setSchool({ name: "", slug: "", email: "" }); }
  async function invite(event: FormEvent) { event.preventDefault(); if (await submit("/b2b/enrollments/invite", { studentEmail }, "Student invitation sent.")) setStudentEmail(""); }
  async function createCode(event: FormEvent) { event.preventDefault(); if (await submit("/referrals/codes", { code, schoolId: business?.instructor?.schoolId || undefined }, business?.instructor ? "This month's school referral code is ready." : "Referral code created.")) setCode(""); }
  async function claim(event: FormEvent) { event.preventDefault(); if (await submit("/referrals/claim", { code: claimCode }, "Referral code claimed.")) setClaimCode(""); }
  async function accept(id: string) { await submit(`/b2b/enrollments/${id}/accept`, {}, "School invitation accepted."); }
  return <section className="dashboard-card dashboard-wide partnership-card"><div className="dashboard-card-title"><div><span className="small-label">PARTNERSHIPS</span><h2>Driving-school workspace</h2></div><span className="history-caption">Instructor + learner tools</span></div>{business?.instructor ? <div className="partnership-school"><div><strong>{business.instructor.schoolName}</strong><small>{business.instructor.schoolSlug} · {business.instructor.status}</small></div><form onSubmit={invite}><input required type="email" placeholder="student@email.com" value={studentEmail} onChange={(event) => setStudentEmail(event.target.value)} /><button className="button button-small" disabled={busy}>Invite student</button></form></div> : <form className="partnership-form" onSubmit={createSchool}><p>Create a school workspace to invite learners and track enrolments.</p><input required placeholder="School name" value={school.name} onChange={(event) => setSchool({ ...school, name: event.target.value })} /><input required placeholder="school-slug" value={school.slug} onChange={(event) => setSchool({ ...school, slug: event.target.value })} /><input type="email" placeholder="School email (optional)" value={school.email} onChange={(event) => setSchool({ ...school, email: event.target.value })} /><button className="button button-small" disabled={busy}>Create workspace</button></form>}{business?.studentEnrollments?.map((item) => <div className="student-invite" key={item.id}><span>{item.schoolName}</span><small>{item.instructorName || item.instructorEmail} invited you</small>{item.status === "INVITED" && <button onClick={() => void accept(item.id)}>Accept</button>}</div>)}<div className="referral-tools"><div><span className="small-label">REFERRALS</span><strong>Grow your learner network</strong>{monthlyCode && <small className="monthly-referral-code">Current month: <b>{monthlyCode}</b></small>}</div><form onSubmit={createCode}><input required placeholder="NEWCODE" value={code} onChange={(event) => setCode(event.target.value)} /><button className="button button-small" disabled={busy}>Create code</button></form><form onSubmit={claim}><input required placeholder="Claim a code" value={claimCode} onChange={(event) => setClaimCode(event.target.value)} /><button className="button button-small button-muted" disabled={busy}>Claim</button></form></div>{referrals.length > 0 && <div className="referral-list">{referrals.map((item) => <span key={item.id}><strong>{item.code}</strong> · {item.referralCount} referrals · €{(item.commissionCents / 100).toFixed(2)}</span>)}</div>}{message && <p className="account-message account-success-text">{message}</p>}</section>;
}
